<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
    JavaScript解析或运行时，一旦发生错误，引擎就会抛出一个错误对象。JavaScript原生提供Error构造函数，所有抛出的错误都是这个构造函数的实例。
    <script>
        var err = new Error('出错了');
        err.message //"出错了"
    </script>
<p>
    上面代码中，我们调用Error构造函数，生成一个实例对象err。Error构造函数接受一个参数，表示错误提示，可以从实例的message属性读到这个参数。抛出Error实例对象以后，整个程序就中断在发生错误的地方，不再往下执行。

    JavaScript 语言标准只提到，Error实例对象必须有message属性，表示出错时的提示信息，没有提到其他属性。大多数 JavaScript 引擎，对Error实例还提供name和stack属性，分别表示错误的名称和错误的堆栈，但它们是非标准的，不是每种实现都有。

    message：错误提示信息
    name：错误名称（非标准属性）
    stack：错误的堆栈（非标准属性）
    使用name和message这两个属性，可以对发生什么错误有一个大概的了解。

    if (error.name) {
    console.log(error.name + ': ' + error.message);
    }
    stack属性用来查看错误发生时的堆栈。

    function throwit() {
    throw new Error('');
    }

    function catchit() {
    try {
    throwit();
    } catch(e) {
    console.log(e.stack); // print stack trace
    }
    }

    catchit()
    // Error
    //    at throwit (~/examples/throwcatch.js:9:11)
    //    at catchit (~/examples/throwcatch.js:3:9)
    //    at repl:1:5
    上面代码中，错误堆栈的最内层是throwit函数，然后是catchit函数，最后是函数的运行环境。
</p>
</body>
</html>