<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
<p>一旦发生错误，程序就中止执行了。JavaScript提供了try...catch结构，允许对错误进行处理，选择是否往下执行。</p>
<p>
        try {
            throw new Error('出错了！');
        } catch (e) {
            console.log(e.name + "：" + e.message);
            console.log(e.stack);
        }
    // Error: 出错了!
    //   at <anonymous>:3:9
    //   ...
</p>
<p>
    上面代码中，try代码块抛出错误（上例用的是throw语句），JavaScript 引擎就立即把代码的执行，转到catch代码块，或者说错误被catch代码块捕获了。catch接受一个参数，表示try代码块抛出的值。

    如果你不确定某些代码是否会报错，就可以把它们放在try...catch代码块之中，便于进一步对错误进行处理。
</p>
</body>
</html>